In [39]:
import pandas as pd
import sys
import os

In [40]:
clean_hydro_data = pd.read_csv("valid_Data/hydrometric.csv")
clean_weather_data = pd.read_csv("valid_Data/weather.csv")

In [41]:
clean_hydro_data

,Date,Station ID,Station Name,Province,Latitude,Longitude,Daily Discharge,SYM1,Daily Water Level,SYM2,match key
0,2013-01-01,08HB006,PUNTLEDGE RIVER AT COURTENAY,BC,49.68803,-125.03419,23.2,NaN,20.153,NaN,4
1,2013-01-02,08HB006,PUNTLEDGE RIVER AT COURTENAY,BC,49.68803,-125.03419,21.3,NaN,20.126,NaN,4
2,2013-01-03,08HB006,PUNTLEDGE RIVER AT COURTENAY,BC,49.68803,-125.03419,20.9,NaN,20.120,NaN,4
3,2013-01-04,08HB006,PUNTLEDGE RIVER AT COURTENAY,BC,49.68803,-125.03419,21.0,NaN,20.122,NaN,4
4,2013-01-05,08HB006,PUNTLEDGE RIVER AT COURTENAY,BC,49.68803,-125.03419,21.8,NaN,20.133,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...
32131,2023-12-27,08NH118,DUNCAN RIVER BELOW LARDEAU RIVER,BC,50.23286,-116.95519,160.0,NaN,2.201,NaN,2
32132,2023-12-28,08NH118,DUNCAN RIVER BELOW LARDEAU RIVER,BC,50.23286,-116.95519,161.0,NaN,2.205,NaN,2
32133,2023-12-29,08NH118,DUNCAN RIVER BELOW LARDEAU RIVER,BC,50.23286,-116.95519,160.0,NaN,2.204,NaN,2
32134,2023-12-30,08NH118,DUNCAN RIVER BELOW LARDEAU RIVER,BC,50.23286,-116.95519,160.0,NaN,2.201,NaN,2
32135,2023-12-31,08NH118,DUNCAN RIVER BELOW LARDEAU RIVER,BC,50.23286,-116.95519,159.0,NaN,2.196,NaN,2

In [42]:
clean_weather_data

,Station Name,Latitude,Longitude,Date,MIN_TEMPERATURE,MAX_TEMPERATURE,MEAN_TEMPERATURE,TOTAL_PRECIPITATION,TOTAL_RAIN,TOTAL_SNOW,SNOW_ON_GROUND,match key
0,CAMPBELL RIVER A,49.951944,-125.273056,2013-01-01 00:00:00,1.2,3.1,2.2,0.0,0.0,0.0,3.0,3
1,CAMPBELL RIVER A,49.951944,-125.273056,2013-01-02 00:00:00,0.0,3.4,1.7,0.0,0.0,0.0,3.0,3
2,CAMPBELL RIVER A,49.951944,-125.273056,2013-01-03 00:00:00,0.8,2.7,1.8,1.6,1.6,0.0,0.0,3
3,CAMPBELL RIVER A,49.951944,-125.273056,2013-01-04 00:00:00,1.3,5.2,3.3,6.8,6.8,0.0,0.0,3
4,CAMPBELL RIVER A,49.951944,-125.273056,2013-01-05 00:00:00,1.3,5.8,3.6,7.4,7.4,0.0,0.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...
20379,QUINSAM RIVER HATCHERY,50.016111,-125.303889,2023-12-27 00:00:00,4.5,9.5,7.0,40.4,40.4,0.0,0.0,5
20380,QUINSAM RIVER HATCHERY,50.016111,-125.303889,2023-12-28 00:00:00,8.5,10.0,9.3,10.8,10.8,0.0,0.0,5
20381,QUINSAM RIVER HATCHERY,50.016111,-125.303889,2023-12-29 00:00:00,7.0,10.0,8.5,11.4,11.4,0.0,0.0,5
20382,QUINSAM RIVER HATCHERY,50.016111,-125.303889,2023-12-30 00:00:00,7.0,11.5,9.3,1.4,1.4,0.0,0.0,5
20383,QUINSAM RIVER HATCHERY,50.016111,-125.303889,2023-12-31 00:00:00,1.5,8.5,5.0,0.2,0.2,0.0,0.0,5

In [43]:
clean_hydro_data[clean_hydro_data["match key"] == 3]

,Date,Station ID,Station Name,Province,Latitude,Longitude,Daily Discharge,SYM1,Daily Water Level,SYM2,match key
12051,2013-01-01,08HD011,OYSTER RIVER BELOW WOODHUS CREEK,BC,49.89458,-125.24175,4.07,NaN,0.988,NaN,3
12052,2013-01-02,08HD011,OYSTER RIVER BELOW WOODHUS CREEK,BC,49.89458,-125.24175,3.90,NaN,0.983,NaN,3
12053,2013-01-03,08HD011,OYSTER RIVER BELOW WOODHUS CREEK,BC,49.89458,-125.24175,3.63,NaN,0.975,NaN,3
12054,2013-01-04,08HD011,OYSTER RIVER BELOW WOODHUS CREEK,BC,49.89458,-125.24175,3.57,NaN,0.973,NaN,3
12055,2013-01-05,08HD011,OYSTER RIVER BELOW WOODHUS CREEK,BC,49.89458,-125.24175,4.32,NaN,0.996,NaN,3
...,...,...,...,...,...,...,...,...,...,...,...
16063,2023-12-27,08HD011,OYSTER RIVER BELOW WOODHUS CREEK,BC,49.89458,-125.24175,68.60,NaN,1.764,NaN,3
16064,2023-12-28,08HD011,OYSTER RIVER BELOW WOODHUS CREEK,BC,49.89458,-125.24175,145.00,NaN,2.169,NaN,3
16065,2023-12-29,08HD011,OYSTER RIVER BELOW WOODHUS CREEK,BC,49.89458,-125.24175,110.00,NaN,2.014,NaN,3
16066,2023-12-30,08HD011,OYSTER RIVER BELOW WOODHUS CREEK,BC,49.89458,-125.24175,109.00,NaN,2.002,NaN,3
16067,2023-12-31,08HD011,OYSTER RIVER BELOW WOODHUS CREEK,BC,49.89458,-125.24175,48.40,NaN,1.628,NaN,3

In [44]:
clean_weather_data[clean_weather_data["match key"] == 3]

,Station Name,Latitude,Longitude,Date,MIN_TEMPERATURE,MAX_TEMPERATURE,MEAN_TEMPERATURE,TOTAL_PRECIPITATION,TOTAL_RAIN,TOTAL_SNOW,SNOW_ON_GROUND,match key
0,CAMPBELL RIVER A,49.951944,-125.273056,2013-01-01 00:00:00,1.2,3.1,2.2,0.0,0.0,0.0,3.0,3
1,CAMPBELL RIVER A,49.951944,-125.273056,2013-01-02 00:00:00,0.0,3.4,1.7,0.0,0.0,0.0,3.0,3
2,CAMPBELL RIVER A,49.951944,-125.273056,2013-01-03 00:00:00,0.8,2.7,1.8,1.6,1.6,0.0,0.0,3
3,CAMPBELL RIVER A,49.951944,-125.273056,2013-01-04 00:00:00,1.3,5.2,3.3,6.8,6.8,0.0,0.0,3
4,CAMPBELL RIVER A,49.951944,-125.273056,2013-01-05 00:00:00,1.3,5.8,3.6,7.4,7.4,0.0,0.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...
3931,CAMPBELL RIVER A,49.951944,-125.273056,2023-12-27 00:00:00,4.0,9.0,6.5,39.0,39.0,0.0,0.0,3
3932,CAMPBELL RIVER A,49.951944,-125.273056,2023-12-28 00:00:00,8.0,9.0,8.5,13.2,13.2,0.0,0.0,3
3933,CAMPBELL RIVER A,49.951944,-125.273056,2023-12-29 00:00:00,8.0,10.0,9.0,14.5,14.5,0.0,0.0,3
3934,CAMPBELL RIVER A,49.951944,-125.273056,2023-12-30 00:00:00,5.0,12.0,8.5,1.0,1.0,0.0,0.0,3
3935,CAMPBELL RIVER A,49.951944,-125.273056,2023-12-31 00:00:00,0.0,8.5,4.3,0.0,0.0,0.0,0.0,3