In [2]:
import pandas as pd
import sys
import os
import numpy as np

In [60]:
data = pd.read_csv("clean_bc_daily_weather_data/clean_bc_daily_weather_data.csv")

In [4]:
missingFirstDate = []
# loop through all of the stations and see if they're missing the January 1st 2013, if not we can simply
# fill in the missing values with the last valid observation without worrying about incorrectly
# assigning a station name
for station in data["STATION_NAME"].unique():
    if station == 'nan':
        continue
    else:
        if data[data["STATION_NAME"] == station]["LOCAL_DATE"].unique()[0] != '2013-01-01':
            missingFirstDate.append(station)

In [5]:
missingFirstDate

[]

In [6]:
data

,LOCAL_DATE,STATION_NAME,LATITUDE,LONGITUDE,MIN_TEMPERATURE,MAX_TEMPERATURE,MEAN_TEMPERATURE,TOTAL_PRECIPITATION,TOTAL_RAIN,TOTAL_SNOW,SNOW_ON_GROUND
0,2013-01-01,ADDENBROKE ISLAND,51.603528,-127.863861,1.5,5.5,3.5,0.0,0.0,0.0,0.0
1,2013-01-02,ADDENBROKE ISLAND,51.603528,-127.863861,3.0,10.5,6.8,0.0,0.0,0.0,0.0
2,2013-01-03,ADDENBROKE ISLAND,51.603528,-127.863861,2.0,8.0,5.0,7.4,7.4,0.0,0.0
3,2013-01-04,ADDENBROKE ISLAND,51.603528,-127.863861,5.0,8.0,6.5,6.0,6.0,0.0,0.0
4,2013-01-05,ADDENBROKE ISLAND,51.603528,-127.863861,3.5,10.0,6.8,23.0,23.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
224947,2023-12-27,ZEBALLOS MURAUDE CREEK,50.052944,-126.778694,5.0,9.5,7.3,99.6,99.6,0.0,0.0
224948,2023-12-28,ZEBALLOS MURAUDE CREEK,50.052944,-126.778694,7.5,10.5,9.0,36.6,36.6,0.0,0.0
224949,2023-12-29,ZEBALLOS MURAUDE CREEK,50.052944,-126.778694,8.0,11.0,9.5,53.4,53.4,0.0,0.0
224950,2023-12-30,ZEBALLOS MURAUDE CREEK,50.052944,-126.778694,8.0,9.5,8.8,11.0,11.0,0.0,0.0
224951,2023-12-31,ZEBALLOS MURAUDE CREEK,50.052944,-126.778694,2.0,7.0,4.5,1.4,1.4,0.0,0.0

In [7]:
problem = []
for station in data["STATION_NAME"].unique():
    if len(data[data["STATION_NAME"] == station]["LONGITUDE"].unique()) > 1:
        problem.append(station)
    elif len(data[data["STATION_NAME"] == station]["LATITUDE"].unique()) > 1:
        problem.append(station)

In [8]:
problem

[]

In [9]:
len(data)

224952

In [10]:
53 * 4017

212901

In [11]:
len(data["STATION_NAME"].unique())

53

In [12]:
data.groupby(["STATION_NAME","LATITUDE","LONGITUDE"]).count()

,,,LOCAL_DATE,MIN_TEMPERATURE,MAX_TEMPERATURE,MEAN_TEMPERATURE,TOTAL_PRECIPITATION,TOTAL_RAIN,TOTAL_SNOW,SNOW_ON_GROUND
STATION_NAME,LATITUDE,LONGITUDE,,,,,,,,
ADDENBROKE ISLAND,51.603528,-127.863861,4017,4017,4017,4017,4017,4017,4017,4017
ALBERNI ROBERTSON CREEK,49.337225,-124.981969,4017,4017,4017,4017,4017,4017,4017,4017
BARKERVILLE,53.069167,-121.514722,4017,4017,4017,4017,4017,4017,4017,4017
BLUE RIVER A,52.129028,-119.289528,4017,4017,4017,4017,4017,4017,4017,4017
BOAT BLUFF,52.643069,-128.523908,4017,4017,4017,4017,4017,4017,4017,4017
BONILLA ISLAND,53.492750,-130.637694,4017,4017,4017,4017,4017,4017,4017,4017
CAMPBELL RIVER A,49.951944,-125.273056,4017,4017,4017,4017,4017,4017,4017,4017
CAPE BEALE LIGHT,48.786111,-125.216111,4017,4017,4017,4017,4017,4017,4017,4017
CAPE MUDGE,49.998472,-125.195472,4017,4017,4017,4017,4017,4017,4017,4017
CASTLEGAR A,49.296389,-117.632500,4017,4017,4017,4017,4017,4017,4017,4017
CASTLEGAR BCHPA DAM,49.343394,-117.774178,4017,4017,4017,4017,4017,4017,4017,4017
CHEMAINUS,48.935022,-123.741667,4017,4017,4017,4017,4017,4017,4017,4017
CHETWYND A,55.687222,-121.626667,4017,4017,4017,4017,4017,4017,4017,4017
CLOVERDALE EAST,49.109153,-122.697597,4017,4017,4017,4017,4017,4017,4017,4017
COURTENAY PUNTLEDGE,49.686442,-125.032768,4017,4017,4017,4017,4017,4017,4017,4017
DRYAD POINT,52.185001,-128.112224,4017,4017,4017,4017,4017,4017,4017,4017
DUNCAN LAKE DAM,50.238667,-116.971528,4017,4017,4017,4017,4017,4017,4017,4017
EGG ISLAND,51.247222,-127.835361,4017,4017,4017,4017,4017,4017,4017,4017
ENTRANCE ISLAND,49.208911,-123.808892,4017,4017,4017,4017,4017,4017,4017,4017
FORT LANGLEY TELEGRAPH TRAIL,49.144667,-122.551000,4017,4017,4017,4017,4017,4017,4017,4017
FT STEELE DANDY CRK,49.523917,-115.460583,4017,4017,4017,4017,4017,4017,4017,4017
GIBSONS GOWER POINT,49.385581,-123.541389,4017,4017,4017,4017,4017,4017,4017,4017
GOLDEN A,51.299167,-116.982222,4017,4017,4017,4017,4017,4017,4017,4017
HANEY UBC RF ADMIN,49.264472,-122.573167,4017,4017,4017,4017,4017,4017,4017,4017
HOPE SLIDE,49.266667,-121.233333,4017,4017,4017,4017,4017,4017,4017,4017
IVORY ISLAND,52.269733,-128.406675,4017,4017,4017,4017,4017,4017,4017,4017
JELLICOE,49.672778,-120.332778,4017,4017,4017,4017,4017,4017,4017,4017
KAMLOOPS PRATT ROAD,50.629611,-120.172000,4017,4017,4017,4017,4017,4017,4017,4017
KEMANO,53.563056,-127.942778,4017,4017,4017,4017,4017,4017,4017,4017
LANGARA,54.255180,-133.058000,4017,4017,4017,4017,4017,4017,4017,4017
LENNARD ISLAND,49.110556,-125.923333,4017,4017,4017,4017,4017,4017,4017,4017
MERRY ISLAND LIGHTSTATION,49.467508,-123.912511,4017,4017,4017,4017,4017,4017,4017,4017
MICA DAM,52.053056,-118.585278,4017,4017,4017,4017,4017,4017,4017,4017
MISSION WEST ABBEY,49.152501,-122.270556,12051,12051,12051,12051,12051,12051,12051,12051
NELSON RIXEN CREEK,49.512333,-117.398806,4017,4017,4017,4017,4017,4017,4017,4017
NEW DENVER,49.995835,-117.370285,4017,4017,4017,4017,4017,4017,4017,4017
NOOTKA LIGHTSTATION,49.600000,-126.616667,4017,4017,4017,4017,4017,4017,4017,4017
NORTH PENDER ISLAND,48.763900,-123.286669,4017,4017,4017,4017,4017,4017,4017,4017
PACHENA POINT,48.722778,-125.097222,4017,4017,4017,4017,4017,4017,4017,4017
PEACHLAND,49.783333,-119.716667,8034,8034,8034,8034,8034,8034,8034,8034
POWELL RIVER A,49.834169,-124.500278,4017,4017,4017,4017,4017,4017,4017,4017
PRINCETON A,49.467778,-120.512500,4017,4017,4017,4017,4017,4017,4017,4017
QUALICUM R FISH RESEARCH,49.393783,-124.617237,4017,4017,4017,4017,4017,4017,4017,4017
QUATSINO,50.533614,-127.653336,4017,4017,4017,4017,4017,4017,4017,4017
QUATSINO LIGHTSTATION,50.441111,-128.032500,4017,4017,4017,4017,4017,4017,4017,4017
QUINSAM RIVER HATCHERY,50.016111,-125.303889,4017,4017,4017,4017,4017,4017,4017,4017
RED LAKE,50.935000,-120.800000,4017,4017,4017,4017,4017,4017,4017,4017
SPOKIN LAKE 4E,52.183615,-121.686122,4017,4017,4017,4017,4017,4017,4017,4017
SUSKWA VALLEY,55.288611,-127.170556,4017,4017,4017,4017,4017,4017,4017,4017
TRIPLE ISLAND,54.294667,-130.880306,4017,4017,4017,4017,4017,4017,4017,4017
VAVENBY,51.576111,-119.778056,4017,4017,4017,4017,4017,4017,4017,4017
WHISTLER,50.128889,-122.954833,4017,4017,4017,4017,4017,4017,4017,4017
ZEBALLOS MURAUDE CREEK,50.052944,-126.778694,4017,4017,4017,4017,4017,4017,4017,4017

In [13]:
grouped = data.groupby("STATION_NAME").count()
grouped

,LOCAL_DATE,LATITUDE,LONGITUDE,MIN_TEMPERATURE,MAX_TEMPERATURE,MEAN_TEMPERATURE,TOTAL_PRECIPITATION,TOTAL_RAIN,TOTAL_SNOW,SNOW_ON_GROUND
STATION_NAME,,,,,,,,,,
ADDENBROKE ISLAND,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
ALBERNI ROBERTSON CREEK,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
BARKERVILLE,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
BLUE RIVER A,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
BOAT BLUFF,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
BONILLA ISLAND,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
CAMPBELL RIVER A,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
CAPE BEALE LIGHT,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
CAPE MUDGE,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
CASTLEGAR A,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
CASTLEGAR BCHPA DAM,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
CHEMAINUS,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
CHETWYND A,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
CLOVERDALE EAST,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
COURTENAY PUNTLEDGE,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
DRYAD POINT,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
DUNCAN LAKE DAM,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
EGG ISLAND,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
ENTRANCE ISLAND,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
FORT LANGLEY TELEGRAPH TRAIL,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
FT STEELE DANDY CRK,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
GIBSONS GOWER POINT,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
GOLDEN A,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
HANEY UBC RF ADMIN,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
HOPE SLIDE,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
IVORY ISLAND,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
JELLICOE,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
KAMLOOPS PRATT ROAD,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
KEMANO,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
LANGARA,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
LENNARD ISLAND,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
MERRY ISLAND LIGHTSTATION,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
MICA DAM,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
MISSION WEST ABBEY,12051,12051,12051,12051,12051,12051,12051,12051,12051,12051
NELSON RIXEN CREEK,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
NEW DENVER,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
NOOTKA LIGHTSTATION,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
NORTH PENDER ISLAND,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
PACHENA POINT,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
PEACHLAND,8034,8034,8034,8034,8034,8034,8034,8034,8034,8034
POWELL RIVER A,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
PRINCETON A,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
QUALICUM R FISH RESEARCH,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
QUATSINO,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
QUATSINO LIGHTSTATION,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
QUINSAM RIVER HATCHERY,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
RED LAKE,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
SPOKIN LAKE 4E,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
SUSKWA VALLEY,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
TRIPLE ISLAND,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
VAVENBY,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
WHISTLER,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017
ZEBALLOS MURAUDE CREEK,4017,4017,4017,4017,4017,4017,4017,4017,4017,4017

In [51]:
duplicate_stations = grouped[grouped["LOCAL_DATE"] != 4017].index
duplicate_stations

Index(['MISSION WEST ABBEY', 'PEACHLAND'], dtype='object', name='STATION_NAME')

In [56]:
data = data[~data["STATION_NAME"].isin(duplicate_stations)]
len(data)

204867

In [15]:
print(len(data["STATION_NAME"].unique()))
print(len(data["LATITUDE"].unique()))
print(len(data["LONGITUDE"].unique()))

53
53
53

### ISSUE 1
Duplicate rows for "STATION_NAME" == "MISSION WEST ABBEY"

In [20]:
data[data["STATION_NAME"] == "MISSION WEST ABBEY"]

,LOCAL_DATE,STATION_NAME,LATITUDE,LONGITUDE,MIN_TEMPERATURE,MAX_TEMPERATURE,MEAN_TEMPERATURE,TOTAL_PRECIPITATION,TOTAL_RAIN,TOTAL_SNOW,SNOW_ON_GROUND
132561,2013-01-01,MISSION WEST ABBEY,49.152501,-122.270556,-2.5,2.0,-0.3,0.0,0.0,0.0,0.0
132562,2013-01-02,MISSION WEST ABBEY,49.152501,-122.270556,-1.5,3.5,1.0,0.0,0.0,0.0,0.0
132563,2013-01-03,MISSION WEST ABBEY,49.152501,-122.270556,-2.0,3.0,0.5,12.8,12.8,0.0,0.0
132564,2013-01-04,MISSION WEST ABBEY,49.152501,-122.270556,-0.5,3.0,1.3,5.6,5.6,0.0,0.0
132565,2013-01-05,MISSION WEST ABBEY,49.152501,-122.270556,0.5,4.5,2.5,6.6,6.6,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
144607,2023-12-27,MISSION WEST ABBEY,49.152501,-122.270556,6.0,9.0,7.5,0.0,0.0,0.0,0.0
144608,2023-12-28,MISSION WEST ABBEY,49.152501,-122.270556,6.0,9.0,7.5,0.0,0.0,0.0,0.0
144609,2023-12-29,MISSION WEST ABBEY,49.152501,-122.270556,6.0,9.0,7.5,0.0,0.0,0.0,0.0
144610,2023-12-30,MISSION WEST ABBEY,49.152501,-122.270556,6.0,9.0,7.5,0.0,0.0,0.0,0.0
144611,2023-12-31,MISSION WEST ABBEY,49.152501,-122.270556,6.0,9.0,7.5,0.0,0.0,0.0,0.0

In [63]:
duplicate_data = data[data["STATION_NAME"].isin(duplicate_stations)]
duplicate_data

,LOCAL_DATE,STATION_NAME,LATITUDE,LONGITUDE,MIN_TEMPERATURE,MAX_TEMPERATURE,MEAN_TEMPERATURE,TOTAL_PRECIPITATION,TOTAL_RAIN,TOTAL_SNOW,SNOW_ON_GROUND
132561,2013-01-01,MISSION WEST ABBEY,49.152501,-122.270556,-2.5,2.0,-0.3,0.0,0.0,0.0,0.0
132562,2013-01-02,MISSION WEST ABBEY,49.152501,-122.270556,-1.5,3.5,1.0,0.0,0.0,0.0,0.0
132563,2013-01-03,MISSION WEST ABBEY,49.152501,-122.270556,-2.0,3.0,0.5,12.8,12.8,0.0,0.0
132564,2013-01-04,MISSION WEST ABBEY,49.152501,-122.270556,-0.5,3.0,1.3,5.6,5.6,0.0,0.0
132565,2013-01-05,MISSION WEST ABBEY,49.152501,-122.270556,0.5,4.5,2.5,6.6,6.6,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
172725,2023-12-26,PEACHLAND,49.783333,-119.716667,3.0,5.5,4.3,0.2,0.2,0.0,0.0
172726,2023-12-27,PEACHLAND,49.783333,-119.716667,3.0,5.5,4.3,0.2,0.2,0.0,0.0
172727,2023-12-28,PEACHLAND,49.783333,-119.716667,3.0,5.5,4.3,0.2,0.2,0.0,0.0
172728,2023-12-29,PEACHLAND,49.783333,-119.716667,3.0,5.5,4.3,0.2,0.2,0.0,0.0
172729,2023-12-30,PEACHLAND,49.783333,-119.716667,3.0,5.5,4.3,0.2,0.2,0.0,0.0

In [62]:
data = data.drop_duplicates()

In [33]:
abbey = data[data["STATION_NAME"] == "MISSION WEST ABBEY"]
abbey

,LOCAL_DATE,STATION_NAME,LATITUDE,LONGITUDE,MIN_TEMPERATURE,MAX_TEMPERATURE,MEAN_TEMPERATURE,TOTAL_PRECIPITATION,TOTAL_RAIN,TOTAL_SNOW,SNOW_ON_GROUND
132561,2013-01-01,MISSION WEST ABBEY,49.152501,-122.270556,-2.5,2.0,-0.3,0.0,0.0,0.0,0.0
132562,2013-01-02,MISSION WEST ABBEY,49.152501,-122.270556,-1.5,3.5,1.0,0.0,0.0,0.0,0.0
132563,2013-01-03,MISSION WEST ABBEY,49.152501,-122.270556,-2.0,3.0,0.5,12.8,12.8,0.0,0.0
132564,2013-01-04,MISSION WEST ABBEY,49.152501,-122.270556,-0.5,3.0,1.3,5.6,5.6,0.0,0.0
132565,2013-01-05,MISSION WEST ABBEY,49.152501,-122.270556,0.5,4.5,2.5,6.6,6.6,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
140589,2023-12-26,MISSION WEST ABBEY,49.152501,-122.270556,6.0,9.0,7.5,0.0,0.0,0.0,0.0
140590,2023-12-27,MISSION WEST ABBEY,49.152501,-122.270556,6.0,9.0,7.5,0.0,0.0,0.0,0.0
140591,2023-12-28,MISSION WEST ABBEY,49.152501,-122.270556,6.0,9.0,7.5,0.0,0.0,0.0,0.0
140592,2023-12-29,MISSION WEST ABBEY,49.152501,-122.270556,6.0,9.0,7.5,0.0,0.0,0.0,0.0
140593,2023-12-30,MISSION WEST ABBEY,49.152501,-122.270556,6.0,9.0,7.5,0.0,0.0,0.0,0.0

In [34]:
# examine duplicate case
abbey[abbey["LOCAL_DATE"] == "2013-01-01"]

,LOCAL_DATE,STATION_NAME,LATITUDE,LONGITUDE,MIN_TEMPERATURE,MAX_TEMPERATURE,MEAN_TEMPERATURE,TOTAL_PRECIPITATION,TOTAL_RAIN,TOTAL_SNOW,SNOW_ON_GROUND
132561,2013-01-01,MISSION WEST ABBEY,49.152501,-122.270556,-2.5,2.0,-0.3,0.0,0.0,0.0,0.0
136578,2013-01-01,MISSION WEST ABBEY,49.152501,-122.270556,6.0,9.0,7.5,0.0,0.0,0.0,0.0

In [41]:
unique = abbey.groupby(["LOCAL_DATE","STATION_NAME","LATITUDE","LONGITUDE"]).agg({"MIN_TEMPERATURE":"mean",
        "MAX_TEMPERATURE":"mean","MEAN_TEMPERATURE":"mean","TOTAL_PRECIPITATION":"mean","TOTAL_RAIN":"mean",
        "TOTAL_SNOW":"mean","SNOW_ON_GROUND":"mean"})
unique.reset_index()

,LOCAL_DATE,STATION_NAME,LATITUDE,LONGITUDE,MIN_TEMPERATURE,MAX_TEMPERATURE,MEAN_TEMPERATURE,TOTAL_PRECIPITATION,TOTAL_RAIN,TOTAL_SNOW,SNOW_ON_GROUND
0,2013-01-01,MISSION WEST ABBEY,49.152501,-122.270556,1.75,5.50,3.60,0.0,0.0,0.0,0.0
1,2013-01-02,MISSION WEST ABBEY,49.152501,-122.270556,2.25,6.25,4.25,0.0,0.0,0.0,0.0
2,2013-01-03,MISSION WEST ABBEY,49.152501,-122.270556,2.00,6.00,4.00,6.4,6.4,0.0,0.0
3,2013-01-04,MISSION WEST ABBEY,49.152501,-122.270556,2.75,6.00,4.40,2.8,2.8,0.0,0.0
4,2013-01-05,MISSION WEST ABBEY,49.152501,-122.270556,3.25,6.75,5.00,3.3,3.3,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
4012,2023-12-27,MISSION WEST ABBEY,49.152501,-122.270556,5.50,9.00,7.25,0.0,0.0,0.0,0.0
4013,2023-12-28,MISSION WEST ABBEY,49.152501,-122.270556,6.50,10.00,8.25,0.0,0.0,0.0,0.0
4014,2023-12-29,MISSION WEST ABBEY,49.152501,-122.270556,6.50,11.00,8.75,1.0,1.0,0.0,0.0
4015,2023-12-30,MISSION WEST ABBEY,49.152501,-122.270556,7.25,9.50,8.40,5.8,5.8,0.0,0.0
4016,2023-12-31,MISSION WEST ABBEY,49.152501,-122.270556,6.00,9.00,7.50,0.0,0.0,0.0,0.0